name: ts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pip=23.2.1
  - ase=3.22.1
  - imageio=2.31.1
  - matplotlib-base=3.7.2
  - numpy=1.25.2
  - openbabel=3.1.1
  - scipy=1.11.2
  - networkx=3.1
  - xtb-python=22.1